# Generated by Django 3.1.2 on 2021-02-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathquiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='option3',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option4',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
